export interface RandomUser {
  itemId: number,
  itemTitle: string,
  itemFirstName: string,
  itemLastName: string,
  itemGender: string,
  itemNationality: string,
  itemPhone: string,
  itemEmail: string,
  itemStreet: string,
  itemCity: string,
  itemState: string,
  itemCountry: string,
  itemCounty: string,
  itemCityNumber: number,
  itemPostcode: string,
  itemImage: string,
  itemBirthdate: string,
  itemAge: number,
  itemUserName: string,
  itemPassword: string,
}
